CREATE OR REPLACE STREAM FACILITY_STREAM ON TABLE FACILITY;
CREATE OR REPLACE STREAM PATIENT_STREAM ON TABLE PATIENT;
CREATE OR REPLACE STREAM PROVIDER_STREAM ON TABLE PROVIDER;
CREATE OR REPLACE STREAM MEDICAL_EVENTS_STREAM ON TABLE MEDICAL_EVENTS;
CREATE OR REPLACE STREAM CARE_GAPS_STREAM ON TABLE CARE_GAPS;
CREATE OR REPLACE STREAM CLAIMS_STREAM ON TABLE CLAIMS;
CREATE OR REPLACE STREAM PHARMACY_STREAM ON TABLE PHARMACY;